welcome:
    resource: "@WelcomeBundle/Resources/config/routing.yml"
    prefix:   /welcome

app:
    resource: '@AppBundle/Controller/'
    type: annotation
login:
    pattern:   /login
    defaults:  { _controller: UserBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout